export const AI_COSTS = {
  bio: 1,
  cover_letter: 1,
  linkedin_post: 1,
  outreach: 1,
  discovery_questions: 1,
  late_payment: 1,
  rate_calculator: 1,
  predict_success: 1,
  niche_finder: 1,
  proposal_analyze_job: 1,
  proposal_generate_draft: 1,
  proposal_regenerate: 1,
  proposal_create: 1,
  resume_match: 2,
  contract: 2,
  negotiate: 2,
  scope_creep: 2,
  skill_gap: 2,
  case_study: 2,
  dream_job: 2,
} as const;

export type AiAction = keyof typeof AI_COSTS;

export const AI_ACTION_LABELS: Record<AiAction, string> = {
  bio: "Profile bio",
  cover_letter: "Cover letter",
  linkedin_post: "LinkedIn post",
  outreach: "Outreach message",
  discovery_questions: "Discovery questions",
  late_payment: "Late-payment email",
  rate_calculator: "Rate calculator",
  predict_success: "Job success scoring",
  niche_finder: "Niche finder",
  proposal_analyze_job: "Job analysis",
  proposal_generate_draft: "Proposal draft",
  proposal_regenerate: "Proposal rewrite",
  proposal_create: "Save new proposal",
  resume_match: "Resume match",
  contract: "Contract draft",
  negotiate: "Negotiation script",
  scope_creep: "Scope creep analyzer",
  skill_gap: "Skill gap analysis",
  case_study: "Case study",
  dream_job: "Dream job builder",
};
